jobs:
  include:
    - os: linux
      language: python
      python: "3.7"
      script: python$PY_SFX -c 'from llvmlite import binding; binding.load_library_permanently("libsvml.so")'
    - os: osx
      language: shell
      before_install: export PY_SFX=3
      script: python$PY_SFX -c 'from llvmlite import binding; binding.load_library_permanently("libsvml.dylib")'
    - os: windows
      language: shell
      before_install: choco install python --version 3.7
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      script: python$PY_SFX -c 'from llvmlite import binding; binding.load_library_permanently("libsvml.dll")'

install:
  - pip$PY_SFX install numba
  - numba -s
  - pip$PY_SFX install icc-rt
  - numba -s
